fixed mistakes with not understanding getopt options format

diff --git a/xbps-mini-builder b/xbps-mini-builder
--- a/xbps-mini-builder
+++ b/xbps-mini-builder
@@ -6,10 +6,11 @@ trap 'exec 2>&4 1>&3' 0 1 2 3
 #exec 1>log.out 2>&1
 
 # from https://en.wikipedia.org/wiki/Getopts
-ARG_STRING="bfhr"
-LONG_ARG_STRING="branch-name,force,help,repo"
-ARGS=$(getopt --options ${ARG_STRING} --longoptions ${LONG_ARG_STRING} -- "${@}") || exit
-eval "set -- ${ARGS}"
+ARG_STRING="b:fhr:"
+LONG_ARG_STRING="branch-name:,force,help,repo:"
+ARGS=$(getopt --options=${ARG_STRING} --longoptions=${LONG_ARG_STRING} --name="$0" -- "${@}") || exit
+# setting positional parameters to those parsed by getops
+eval set -- "${ARGS}"
 
 show_usage() {
     cat << _EOF
@@ -65,7 +66,7 @@ GIT_REPO="https://github.com/void-linux/void-packages"
 
 while true; do
     case "${1}" in
-        (-b|--branch)
+        (-b|--branch-name)
             BRANCH=${2}
             shift 2
             ;;
@@ -81,12 +82,16 @@ while true; do
             GIT_REPO=${2}
             shift 2
             ;;
-        (*)
+        (--)
+            shift
             break
+            ;;
+        (*)
+            echo "programming error"
+            exit 3
             ;;
     esac
 done
-
 
 # Jump to the directory that owns this script
 cd "${0%/*}" || exit 1
@@ -161,6 +166,8 @@ if [ -f ../xbps-src.conf ] ; then
     cat ../xbps-src.conf >> etc/conf
 fi
 
+printf "building packages\\n"
+
 if [ $# -eq 0 ] ; then
     while read -r package ; do
         if grep "${package}" ../changed; then
@@ -173,11 +180,12 @@ else
     done
 fi
 
+printf "signing packages\\n"
 
 for folder in "" multilib multilib/nonfree nonfree ; do
     printf "Trying to sign packages in %s\\n" ${folder}
     BINPKGS=""
-    if [ "${BRANCH}" -ne "" ] ; then
+    if [ -n "${BRANCH}" ] ; then
         BINPKGS="hostdir/binpkgs/${BRANCH}/${folder}"
     else
         BINPKGS="hostdir/binpkgs/${folder}"
